#!/bin/bash
name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable


       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Install env
        run: pip install -r requirements.txt

      - name: Install tesseract and chmod permission denied
        run: |
          sudo chmod a+x ./tesseractUbuntu.sh
          ./tesseractUbuntu.sh
          # git config core.filemode false
          # git update-index --chmod=-x /home/runner/work/AutoTest_Admin/AutoTest_Admin/Tesseract-OCR/tesseract.exe
          # git update-index --chmod=+x /home/runner/work/AutoTest_Admin/AutoTest_Admin/Tesseract-OCR/tesseract.exe
          # git config --global user.name "johnny7001"
          # git config --global user.email "theforeverwen@gmail.com"
          # git add -A
          # git commit -m "update"
          # git push
      - name: Running autoTest script
        run:
          python autoTest_NoSemicolon.py

      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config --global user.name "johnny7001"
          git config --global user.email "theforeverwen@gmail.com"
          git add -A
          git commit -m "update"
          git push

      # - name: Read cookies
      #   run: python readCookieImage.py