name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Install env
        run: pip install -r requirements.txt
#        dependencies:
#          -async-generator==1.10
#          -attrs==22.2.0
#          -beautifulsoup4==4.11.2
#          -bs4==0.0.1
#          -certifi==2022.12.7
#          -cffi==1.15.1
#          -charset-normalizer==3.0.1
#          -contourpy==1.0.7
#          -cycler==0.11.0
#          -exceptiongroup==1.1.0
#          -fonttools==4.39.0
#          -h11==0.14.0
#          -idna==3.4
#          -kiwisolver==1.4.4
#          -matplotlib==3.7.1
#          -numpy==1.24.2
#          -opencv-python==4.7.0.72
#          -outcome==1.2.0
#          -packaging==23.0
#          -Pillow==9.4.0
#          -pycparser==2.21
#          -pyparsing==3.0.9
#          -PySocks==1.7.1
#          -pytesseract==0.3.10
#          -python-dateutil==2.8.2
#          -python-dotenv==1.0.0
#          -requests==2.28.2
#          -selenium==4.8.2
#          -six==1.16.0
#          -sniffio==1.3.0
#          -sortedcontainers==2.4.0
#          -soupsieve==2.4
#          -trio==0.22.0
#          -trio-websocket==0.9.2
#          -urllib3==1.26.14
#          -wsproto==1.2.0


      - name: Running the Python script
        run: python autoTest_NoSemicolon.py

      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config --global user.name "johnny7001"
          git config --global user.email "theforeverwen@gmail.com"
          git add -A
          git commit -m "update"
          git push